name: open_meteo_api
description: A Dart API Client for the Open-Meteo API.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_mappable: ^3.2.0
  http: ^0.13.0

dev_dependencies:
  build_runner: ^2.0.0
  dart_mappable_builder: ^3.2.2
  lints: ^2.1.1
  mocktail: ^1.0.0
  test: ^1.16.4
